In [8]:
import players

In [4]:
season_stats.loc[season_stats['Player'] == 'Billy Cunningham*']

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2243,2243,1966.0,Billy Cunningham*,SF,22.0,PHI,80.0,NaN,2134.0,15.7,...,0.634,NaN,NaN,599.0,207.0,NaN,NaN,NaN,301.0,1143.0
2378,2378,1967.0,Billy Cunningham*,SF,23.0,PHI,81.0,NaN,2168.0,19.3,...,0.686,NaN,NaN,589.0,205.0,NaN,NaN,NaN,260.0,1495.0
2518,2518,1968.0,Billy Cunningham*,SF,24.0,PHI,74.0,NaN,2076.0,18.6,...,0.723,NaN,NaN,562.0,187.0,NaN,NaN,NaN,260.0,1400.0
2697,2697,1969.0,Billy Cunningham*,PF,25.0,PHI,82.0,NaN,3345.0,18.7,...,0.737,NaN,NaN,1050.0,287.0,NaN,NaN,NaN,329.0,2034.0
2902,2902,1970.0,Billy Cunningham*,SF,26.0,PHI,81.0,NaN,3194.0,21.0,...,0.729,NaN,NaN,1101.0,352.0,NaN,NaN,NaN,331.0,2114.0
3117,3117,1971.0,Billy Cunningham*,SF,27.0,PHI,81.0,NaN,3090.0,20.5,...,0.734,NaN,NaN,946.0,395.0,NaN,NaN,NaN,328.0,1859.0
3359,3359,1972.0,Billy Cunningham*,SF,28.0,PHI,75.0,NaN,2900.0,21.3,...,0.712,NaN,NaN,918.0,443.0,NaN,NaN,NaN,295.0,1744.0
4163,4163,1975.0,Billy Cunningham*,SF,31.0,PHI,80.0,NaN,2859.0,19.2,...,0.777,130.0,596.0,726.0,442.0,91.0,35.0,NaN,270.0,1563.0
4431,4431,1976.0,Billy Cunningham*,SF,32.0,PHI,20.0,NaN,640.0,16.4,...,0.773,29.0,118.0,147.0,107.0,24.0,10.0,NaN,57.0,274.0

In [6]:
def search(string):
    return season_stats[season_stats['Player'].str.contains(string)==True]